# Generated by Django 2.0.2 on 2018-02-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_share', models.CharField(blank=True, max_length=30)),
                ('descript', models.CharField(blank=True, max_length=30)),
                ('capitalization', models.CharField(blank=True, max_length=30)),
                ('dividends_profit', models.CharField(blank=True, max_length=30)),
                ('dividends_real', models.CharField(blank=True, max_length=30)),
                ('dividends_prognosis', models.CharField(blank=True, max_length=30)),
                ('dividends_date', models.CharField(blank=True, max_length=30)),
                ('real_price', models.CharField(blank=True, max_length=30)),
                ('target_price_short', models.CharField(blank=True, max_length=30)),
                ('target_price_medium', models.CharField(blank=True, max_length=30)),
                ('target_price_long', models.CharField(blank=True, max_length=30)),
                ('potential', models.CharField(blank=True, max_length=30)),
                ('price_change_day', models.CharField(blank=True, max_length=30)),
                ('price_change_quarter', models.CharField(blank=True, max_length=30)),
                ('price_change_january', models.CharField(blank=True, max_length=30)),
                ('trading_volume_day', models.CharField(blank=True, max_length=30)),
                ('trading_volume_quarter', models.CharField(blank=True, max_length=30)),
                ('trading_volume_january', models.CharField(blank=True, max_length=30)),
                ('img_logo', models.FileField(blank=True, upload_to='static/img')),
                ('img_fon', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
