# Generated by Django 2.0.2 on 2018-02-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='img_logo',
            field=models.FileField(blank=True, upload_to='static/media'),
        ),
    ]
