# Generated by Django 2.0.2 on 2018-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20180215_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='price_change_10years',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='share',
            name='price_change_2017',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='share',
            name='price_change_3years',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
