# Generated by Django 2.0.2 on 2018-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_auto_20180215_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='share',
            name='date_of_organization',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='share',
            name='industry',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
