# Generated by Django 2.0.2 on 2018-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_auto_20180215_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='basic_information',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='share',
            name='benefits',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='share',
            name='leadership',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='share',
            name='market_share',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
