# Generated by Django 2.0.2 on 2018-02-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_auto_20180215_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='basic_information',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='share',
            name='benefits',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='share',
            name='leadership',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='share',
            name='market_share',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
