# Generated by Django 2.0.2 on 2018-02-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0006_auto_20180215_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='grafik',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
