# Generated by Django 2.0.2 on 2018-02-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0007_share_grafik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='grafik',
            new_name='grafik_code',
        ),
    ]
