# Generated by Django 2.0.2 on 2018-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0008_auto_20180221_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='grafik_code',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
