# Generated by Django 2.0.2 on 2018-02-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0009_auto_20180221_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='grafik_code',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
